---

- name: "Config actual"

  hosts: ROUTERS
  gather_facts: no

- name: GIT SECTION
  hosts: localhost

  tasks:

    - name: print time
      command: date
      register: time
      changed_when: false
      delegate_to: localhost
      run_once: yes
    - name: git commands
      shell: |
        git add .
        git commit -m "Device Backup on {{time.stdout }}"
        git push
      args:
        chdir: /home/ubuntu/mikrotik-backups
      delegate_to: localhost
      run_once: yes

...

